# Generated by Django 2.2.11 on 2020-03-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('birthday', models.DateTimeField()),
                ('nickname', models.CharField(max_length=200)),
                ('gender', models.IntegerField()),
                ('phone', models.CharField(max_length=200)),
            ],
        ),
    ]
