# Generated by Django 3.0.5 on 2020-05-08 19:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20200508_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(default='2020-05-08 19:38:32', max_length=50, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 19, 38, 32, 137886), verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='interactive',
            name='activeTime',
            field=models.CharField(default='2020-05-08 19:38:32', max_length=50, verbose_name='互动时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='createTime',
            field=models.CharField(default='2020-05-08 19:38:32', max_length=50, verbose_name='创建时间'),
        ),
        migrations.CreateModel(
            name='CommentActive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, '点赞'), (2, '回复评论'), (3, '回复用户')], verbose_name='互动类型')),
                ('content', models.CharField(max_length=200, verbose_name='回复内容')),
                ('time', models.CharField(default='2020-05-08 19:38:32', max_length=50, verbose_name='评论时间')),
                ('commentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toCom', to='myApp.Comment', verbose_name='评论ID')),
                ('fromStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromStu', to='myApp.Student', verbose_name='评论用户')),
                ('toStudent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toStu', to='myApp.Student', verbose_name='回复用户')),
            ],
        ),
    ]
