# Generated by Django 2.2.11 on 2020-04-14 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20200412_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 20, 37, 55, 89524), verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='site',
            name='siteName',
            field=models.CharField(help_text='站点名，比如某市或某学校', max_length=200, verbose_name='站点名称'),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.FileField(default='/img/avatars/default.jpg', upload_to='img/avatars', verbose_name='用户头像'),
        ),
    ]
