# Generated by Django 2.2.11 on 2020-04-14 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20200414_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='currentEducation',
            field=models.SmallIntegerField(choices=[(1, '专科'), (2, '本科'), (3, '硕士'), (4, '博士')], default=2, verbose_name='当前学历'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='studentCard',
            field=models.CharField(max_length=50, null=True, verbose_name='学生证号'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 20, 57, 29, 574886), verbose_name='发送时间'),
        ),
    ]
