# Generated by Django 2.2.11 on 2020-04-14 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_auto_20200414_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 21, 45, 34, 753314), verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已认证'), (2, '未认证'), (3, '锁定'), (0, '注销')], default=2, verbose_name='用户状态'),
        ),
    ]
