# Generated by Django 3.0.5 on 2020-04-25 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_auto_20200425_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 21, 58, 13, 985256), verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='student',
            name='siteList',
            field=models.CharField(default="{'text': '主站', 'value': 1}", help_text='表示当前用户的可用站点', max_length=200, verbose_name='站点'),
        ),
    ]
