# Generated by Django 3.0.5 on 2020-05-12 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_auto_20200511_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hotValue',
            field=models.IntegerField(default=0, verbose_name='热点值'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(default='2020-05-12 19:48:22', max_length=50, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='commentactive',
            name='time',
            field=models.CharField(default='2020-05-12 19:48:22', max_length=50, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 12, 19, 48, 22, 50948), verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='interactive',
            name='activeTime',
            field=models.CharField(default='2020-05-12 19:48:22', max_length=50, verbose_name='互动时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='createTime',
            field=models.CharField(default='2020-05-12 19:48:22', max_length=50, verbose_name='创建时间'),
        ),
    ]
