# Generated by Django 3.0.5 on 2020-04-27 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_auto_20200425_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 20, 26, 31, 113993), verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.IntegerField(choices=[(1, '男性'), (2, '女性'), (0, '不展示')], default=0, help_text='1表示男性，2表示女性, 0表示不展示性别', verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='siteList',
            field=models.CharField(default='[{"siteName":"主站","id":1}]', help_text='表示当前用户的可用站点', max_length=200, verbose_name='站点'),
        ),
    ]
