# Generated by Django 3.0.5 on 2020-05-15 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_auto_20200515_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='unReadPost',
        ),
        migrations.AddField(
            model_name='student',
            name='unReadPost',
            field=models.IntegerField(default=0, verbose_name='未读动态'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(default='2020-05-15 00:04:29', max_length=50, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='commentactive',
            name='time',
            field=models.CharField(default='2020-05-15 00:04:29', max_length=50, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 0, 4, 29, 326990), verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='interactive',
            name='activeTime',
            field=models.CharField(default='2020-05-15 00:04:29', max_length=50, verbose_name='互动时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='createTime',
            field=models.CharField(default='2020-05-15 00:04:29', max_length=50, verbose_name='创建时间'),
        ),
    ]
