# Generated by Django 3.0.5 on 2020-04-30 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_auto_20200427_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 23, 4, 55, 519673), verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.CharField(max_length=50, null=True, verbose_name='生日'),
        ),
    ]
