# Generated by Django 3.0.5 on 2020-05-15 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_auto_20200515_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(default='2020-05-15 00:44:38', max_length=50, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='commentactive',
            name='time',
            field=models.CharField(default='2020-05-15 00:44:38', max_length=50, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 0, 44, 38, 737634), verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='history',
            name='viewTime',
            field=models.DateField(default=datetime.datetime(2020, 5, 15, 0, 44, 38, 739598), verbose_name='浏览时间'),
        ),
        migrations.AlterField(
            model_name='interactive',
            name='activeTime',
            field=models.CharField(default='2020-05-15 00:44:38', max_length=50, verbose_name='互动时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='createTime',
            field=models.CharField(default='2020-05-15 00:44:38', max_length=50, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hotValue',
            field=models.IntegerField(default=1000, verbose_name='热点值'),
        ),
    ]
