# Generated by Django 3.0.5 on 2020-05-03 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_auto_20200501_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 14, 16, 9, 747637), verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='post',
            name='createPlace',
            field=models.CharField(max_length=50, null=True, verbose_name='创建地点'),
        ),
        migrations.AlterField(
            model_name='post',
            name='createTime',
            field=models.DateField(default=datetime.datetime(2020, 5, 3, 14, 16, 9, 747637), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='forwards',
            field=models.IntegerField(default=0, verbose_name='转发数'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imgs',
            field=models.TextField(null=True, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='post',
            name='introduction',
            field=models.CharField(max_length=50, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(max_length=200, null=True, verbose_name='标签'),
        ),
    ]
