# Generated by Django 3.0.5 on 2020-05-06 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_auto_20200506_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 21, 53, 30, 281820), verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='createTime',
            field=models.CharField(default='2020-05-06 21:53:30', max_length=50, verbose_name='创建时间'),
        ),
    ]
