# Generated by Django 3.0.5 on 2020-05-06 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_auto_20200506_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stars',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 22, 9, 1, 764227), verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='createTime',
            field=models.CharField(default='2020-05-06 22:09:01', max_length=50, verbose_name='创建时间'),
        ),
    ]
