# Generated by Django 3.0.5 on 2020-05-06 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_auto_20200506_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 22, 36, 12, 17614), verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='interactive',
            name='activeTime',
            field=models.CharField(default='2020-05-06 22:36:12', max_length=50, verbose_name='互动时间'),
        ),
        migrations.AlterField(
            model_name='interactive',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '点赞'), (2, '评论'), (3, '收藏'), (4, '转发')], verbose_name='互动类型'),
        ),
        migrations.AlterField(
            model_name='post',
            name='createTime',
            field=models.CharField(default='2020-05-06 22:36:12', max_length=50, verbose_name='创建时间'),
        ),
    ]
